=== lambertlb/CharacterManager/CharacterTemplates/CharacterTemplate.json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"PersonalInformation": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string"
				},
				"Race": {
					"type": "string"
				},
				"Age": {
					"type": "integer"
				},
				"Alignment": {
					"type": "string"
				},
				"Deity": {
					"type": "string"
				},
				"Weight": {
					"type": "number"
				},
				"Experience": {
					"type": "integer"
				},
				"Gender": {
					"type": "string"
				},
				"Money": {
					"type": "object",
					"properties": {
						"Platinum": {
							"type": "integer"
						},
						"Gold": {
							"type": "integer"
						},
						"Electrum": {
							"type": "integer"
						},
						"Silver": {
							"type": "integer"
						},
						"Copper": {
							"type": "integer"
						}
					},
					"required": [
						"Copper",
						"Electrum",
						"Gold",
						"Platinum",
						"Silver"
					]
				}
			},
			"required": [
				"Age",
				"Alignment",
				"Deity",
				"Experience",
				"Gender",
				"Money",
				"Name",
				"Race",
				"Weight"
			]
		},
		"Health": {
			"type": "object",
			"properties": {
				"TotalHp": {
					"type": "integer"
				},
				"CurrentHp": {
					"type": "integer"
				},
				"TemporaryHp": {
					"type": "integer"
				}
			},
			"required": [
				"CurrentHp",
				"TemporaryHp",
				"TotalHp"
			]
		},
		"Defense": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"Offense": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"Skills": {
			"type": "object",
			"properties": {
				"Acrobatics": {
					"type": "integer"
				},
				"AnimalHandling": {
					"type": "integer"
				},
				"Arcana": {
					"type": "integer"
				},
				"Athletics": {
					"type": "integer"
				},
				"Deception": {
					"type": "integer"
				},
				"History": {
					"type": "integer"
				},
				"Insight": {
					"type": "integer"
				},
				"Intimidation": {
					"type": "integer"
				},
				"Investigation": {
					"type": "integer"
				},
				"Medicine": {
					"type": "integer"
				},
				"Nature": {
					"type": "integer"
				},
				"Perception": {
					"type": "integer"
				},
				"Performance": {
					"type": "integer"
				},
				"Persuasion": {
					"type": "integer"
				},
				"Religion": {
					"type": "integer"
				},
				"SleightofHand": {
					"type": "integer"
				},
				"Stealth": {
					"type": "integer"
				},
				"Survival": {
					"type": "integer"
				}
			},
			"required": [
				"Acrobatics",
				"AnimalHandling",
				"Arcana",
				"Athletics",
				"Deception",
				"History",
				"Insight",
				"Intimidation",
				"Investigation",
				"Medicine",
				"Nature",
				"Perception",
				"Performance",
				"Persuasion",
				"Religion",
				"SleightofHand",
				"Stealth",
				"Survival"
			]
		}
	},
	"required": [
		"Defense",
		"Health",
		"Offense",
		"PersonalInformation",
		"Skills"
	]
}

=== lambertlb/CharacterManager/test/TestSavedCharacters/Character_1.json
{
    "PersonalInformation": {
        "Name": "Fred FlintStone",
        "Race": "Human",
        "Age": 22,
        "Alignment": "Neutral",
        "Deity": "Sune",
        "Weight": 110.5,
        "Experience": 1000,
        "Gender": "Male",
        "Money": {
            "Platinum": 5,
            "Gold": 200,
            "Electrum": 50,
            "Silver": 40,
            "Copper": 20
        }
    },
    "Health": {
        "TotalHp": 100,
        "CurrentHp": 50,
        "TemporaryHp": 10
    },
    "Defense": [
        "Plate Mail",
        "Tower Shield"
    ],
    "Offense": [
        "Long Sword",
        "Long Bow",
        "Unarmed"
    ],
    "Skills": {
        "Acrobatics": 10,
        "AnimalHandling": 10,
        "Arcana": 10,
        "Athletics": 10,
        "Deception": 10,
        "History": 10,
        "Insight": 10,
        "Intimidation": 10,
        "Investigation": 10,
        "Medicine": 10,
        "Nature": 10,
        "Perception": 10,
        "Performance": 10,
        "Persuasion": 10,
        "Religion": 10,
        "SleightofHand": 10,
        "Stealth": 10,
        "Survival": 10
    }
}
